---
applications:
- type: internal-support-service
  instances: 1
  blue_green_deploy: false
  memory: 1024M
  disk_quota: 20GB
  services:
    - kafka

  env:
    JAVA_OPTS: -Djava.security.auth.login.config=./kafka_client_jaas.conf
